[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Base crate for the 'swc' crate. This is not a public API."
documentation = "https://rustdoc.swc.rs/swc_compiler_base/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_compiler_base"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.8.0"

[features]
node = ["napi", "napi-derive"]

[dependencies]
anyhow    = "1.0.81"
base64    = "0.21.0"
once_cell = "1"
pathdiff  = "0.2.0"
serde     = { version = "1.0.197", features = ["derive"] }
sourcemap = "8.0"

swc_atoms = { version = "0.6.5", path = "../swc_atoms" }
swc_common = { version = "0.33.20", path = "../swc_common", features = [
  "sourcemap",
] }
swc_config = { version = "0.1.11", path = "../swc_config" }
swc_ecma_ast = { version = "0.113.0", path = "../swc_ecma_ast" }
swc_ecma_codegen = { version = "0.149.0", path = "../swc_ecma_codegen" }
swc_ecma_minifier = { version = "0.193.0", path = "../swc_ecma_minifier" }
swc_ecma_parser = { version = "0.144.0", path = "../swc_ecma_parser" }
swc_ecma_visit = { version = "0.99.0", path = "../swc_ecma_visit" }
swc_timer = { version = "0.21.21", path = "../swc_timer" }

  [dependencies.napi-derive]
  default-features = false
  features         = ["type-def"]
  optional         = true
  version          = "2.0.0"

  [dependencies.napi]
  default-features = false
  features         = ["napi3"]
  optional         = true
  version          = "2.0.0"
