[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "rust port of babel and closure compiler."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_optimization/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_ecma_transforms_module"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.181.0"

[lib]
bench = false

[dependencies]
Inflector  = "0.11.4"
anyhow     = "1.0.81"
bitflags   = "2.5.0"
indexmap   = "2.0.0"
is-macro   = "0.3.5"
path-clean = "0.1.0"
pathdiff   = "0.2.0"
regex      = "1"
serde      = { version = "1.0.197", features = ["derive"] }
tracing    = "0.1.40"

swc_atoms = { version = "0.6.5", path = "../swc_atoms" }
swc_cached = { version = "0.3.19", path = "../swc_cached" }
swc_common = { version = "0.33.20", path = "../swc_common" }
swc_ecma_ast = { version = "0.113.0", path = "../swc_ecma_ast" }
swc_ecma_loader = { version = "0.45.23", path = "../swc_ecma_loader", features = [
  "node",
] }
swc_ecma_parser = { version = "0.144.0", path = "../swc_ecma_parser" }
swc_ecma_transforms_base = { version = "0.138.0", path = "../swc_ecma_transforms_base" }
swc_ecma_utils = { version = "0.128.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "0.99.0", path = "../swc_ecma_visit" }

[dev-dependencies]
indexmap   = { version = "2.0.0", features = ["serde"] }
serde_json = "1"

swc_ecma_loader = { version = "0.45.23", path = "../swc_ecma_loader", features = [
  "node",
  "tsc",
] }
swc_ecma_transforms_compat = { version = "0.164.0", path = "../swc_ecma_transforms_compat" }
swc_ecma_transforms_testing = { version = "0.141.0", path = "../swc_ecma_transforms_testing" }
testing = { version = "0.35.21", path = "../testing/" }
